apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: homelab-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.2.210-192.168.2.250  # 分配给 LoadBalancer 的外部 IP

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - homelab-ip-pool

