apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: apps
  name: kvrocks-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  nfs:
    server: 192.168.2.101   # 你的 NFS 服务器
    path: /nfs/kvrocks-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: apps
  name: kvrocks-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
